#!/bin/bash -l
#SBATCH -p debug 		# change this option for non-debug runs
#SBATCH -t 00:1:00		# adjust the amount of time as necessary
#SBATCH -N 1    		# adjust the number of nodes per test (e.g. start with 1, 2, ...)
#SBATCH -A mp309
#SBATCH -o mpi.%j.stdout
#SBATCH -e mpi.%j.error

srun -n 5 -N 1 ./a.out 1 500 2 5


# -n : number of MPI processes
# -c : number of OpenMP threads
# -N : number of nodes
